const blood_donation_club = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    blood_group: "A+",
    location: "New York",
    phone_number: "0123456789",
    last_donate: 5,
    donation_list: {
      patient_1: "Mary Smith",
      patient_2: "David Johnson",
    },
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 25,
    blood_group: "B+",
    location: "Los Angeles",
    phone_number: "0987654321",
    last_donate: 12,
    donation_list: {
      patient_1: "Robert Williams",
      patient_2: "Emily Davis",
    },
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 35,
    blood_group: "O+",
    location: "Chicago",
    phone_number: "0123987654",
    last_donate: 20,
    donation_list: {
      patient_1: "Sarah Anderson",
      patient_2: "Daniel Martinez",
    },
  },
  {
    id: 4,
    name: "Jennifer Brown",
    age: 28,
    blood_group: "AB+",
    location: "Houston",
    phone_number: "0456123789",
    last_donate: 8,
    donation_list: {
      patient_1: "Christopher Thompson",
      patient_2: "Olivia Clark",
    },
  },
  {
    id: 5,
    name: "William Davis",
    age: 32,
    blood_group: "A-",
    location: "San Francisco",
    phone_number: "0897654321",
    last_donate: 15,
    donation_list: {
      patient_1: "Sophia Rodriguez",
      patient_2: "Matthew White",
    },
  },
  {
    id: 6,
    name: "Olivia Wilson",
    age: 27,
    blood_group: "B-",
    location: "Seattle",
    phone_number: "0234987654",
    last_donate: 9,
    donation_list: {
      patient_1: "Ethan Green",
      patient_2: "Ava Harris",
    },
  },
  {
    id: 7,
    name: "James Thompson",
    age: 31,
    blood_group: "O-",
    location: "Boston",
    phone_number: "0412785690",
    last_donate: 18,
    donation_list: {
      patient_1: "Mia Martin",
      patient_2: "Alexander Lewis",
    },
  },
  {
    id: 8,
    name: "Emma Clark",
    age: 29,
    blood_group: "AB-",
    location: "Dallas",
    phone_number: "0987432165",
    last_donate: 6,
    donation_list: {
      patient_1: "William Johnson",
      patient_2: "Isabella Martinez",
    },
  },
  {
    id: 9,
    name: "Daniel Garcia",
    age: 33,
    blood_group: "A+",
    location: "Miami",
    phone_number: "0123798564",
    last_donate: 14,
    donation_list: {
      patient_1: "Sophia Taylor",
      patient_2: "Noah Harris",
    },
  },
  {
    id: 10,
    name: "Emily Brown",
    age: 26,
    blood_group: "B+",
    location: "Atlanta",
    phone_number: "0456213987",
    last_donate: 10,
    donation_list: {
      patient_1: "Emma Wilson",
      patient_2: "Michael Davis",
    },
  },
  {
    id: 11,
    name: "Alexander Anderson",
    age: 30,
    blood_group: "O+",
    location: "Denver",
    phone_number: "0897654321",
    last_donate: 11,
    donation_list: {
      patient_1: "Olivia Thompson",
      patient_2: "James Green",
    },
  },
  {
    id: 12,
    name: "Samantha Taylor",
    age: 28,
    blood_group: "AB+",
    location: "Phoenix",
    phone_number: "0234789561",
    last_donate: 17,
    donation_list: {
      patient_1: "Ethan Wilson",
      patient_2: "Ava Lewis",
    },
  },
  {
    id: 13,
    name: "David Wilson",
    age: 32,
    blood_group: "A-",
    location: "Las Vegas",
    phone_number: "0412987654",
    last_donate: 7,
    donation_list: {
      patient_1: "Sophia Garcia",
      patient_2: "Noah Anderson",
    },
  },
  {
    id: 14,
    name: "Mia Moore",
    age: 27,
    blood_group: "B-",
    location: "San Diego",
    phone_number: "0987564312",
    last_donate: 16,
    donation_list: {
      patient_1: "William Moore",
      patient_2: "Isabella Davis",
    },
  },
  {
    id: 15,
    name: "James Rodriguez",
    age: 31,
    blood_group: "O-",
    location: "Philadelphia",
    phone_number: "0123498765",
    last_donate: 13,
    donation_list: {
      patient_1: "Emma Thompson",
      patient_2: "Michael Green",
    },
  },
  {
    id: 16,
    name: "Emily Lewis",
    age: 29,
    blood_group: "AB-",
    location: "Washington",
    phone_number: "0456128739",
    last_donate: 4,
    donation_list: {
      patient_1: "Alexander Moore",
      patient_2: "Samantha Harris",
    },
  },
  {
    id: 17,
    name: "Daniel Harris",
    age: 33,
    blood_group: "A+",
    location: "Chicago",
    phone_number: "0897432165",
    last_donate: 19,
    donation_list: {
      patient_1: "Mia Wilson",
      patient_2: "James Davis",
    },
  },
  {
    id: 18,
    name: "Olivia Davis",
    age: 26,
    blood_group: "B+",
    location: "Houston",
    phone_number: "0234987561",
    last_donate: 8,
    donation_list: {
      patient_1: "Emily Martin",
      patient_2: "Daniel Thompson",
    },
  },
  {
    id: 19,
    name: "Michael Thompson",
    age: 30,
    blood_group: "O+",
    location: "San Francisco",
    phone_number: "0412789635",
    last_donate: 12,
    donation_list: {
      patient_1: "Olivia Wilson",
      patient_2: "James Clark",
    },
  },
  {
    id: 20,
    name: "Sophia Anderson",
    age: 28,
    blood_group: "AB+",
    location: "Los Angeles",
    phone_number: "0987654321",
    last_donate: 15,
    donation_list: {
      patient_1: "Daniel Harris",
      patient_2: "Emily Garcia",
    },
  },
];

// -------------------- filter 
